# Generated by Django 4.2.4 on 2023-08-24 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0002_alter_english_synonyms_alter_english_translations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="english",
            name="synonyms",
            field=models.ManyToManyField(blank=True, to="words.english"),
        ),
        migrations.AlterField(
            model_name="english",
            name="translations",
            field=models.ManyToManyField(
                blank=True, related_name="translations", to="words.turkish"
            ),
        ),
        migrations.AlterField(
            model_name="wordbox",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="friends_wb", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="wordbox",
            name="words",
            field=models.ManyToManyField(blank=True, to="words.english"),
        ),
    ]
