# Generated by Django 4.2.4 on 2023-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0003_alter_english_synonyms_alter_english_translations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
