# Generated by Django 4.2.4 on 2023-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0005_alter_singlewordgame_number_of_play"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlewordgame",
            name="number_of_play",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
